baseurl = "http://goparker.com/"
RelativeURLs=true
CanonifyURLs=true
DefaultContentLanguage = "en"
title = "goParker"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = false

#[permalinks]
#  post = "post/:year/:month/:day/:title/"

[Params]
  subtitle = "We've gone Parker, have you?"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = false
  
  readingTime = true
  socialShare = false


[Author]
  name = "David Parker"
  website = "http://goparker.com"
  #email = "david@goparker.com"
  github = "davidparkerdr"
  twitter = "davidparkerdr"
  linkedin = "davidparkerdr"
  youtube = "user/DavidParkerDr"
  

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "post"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

